# @format
---
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:prettier/recommended
  - prettier/prettier
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules:
  react/display-name: 'off'
settings:
  import/resolver:
    node:
      paths:
        - src
